import json

class MockActuatorController:
    """Simulates a hardware controller for IoT devices."""
    def execute_command(self, command_name):
        if not command_name:
            print("[WARN] Received empty command. No action taken.")
            return False
        
        # Simulate hardware response
        print(f"Hardware Action Executed: [{command_name}]")
        return True

def process_actuation_command(action_data):
    """
    Parses a structured symbolic command and routes it to the mock controller.
    Supports both JSON strings and dictionaries.
    """
    if isinstance(action_data, str):
        try:
            action_data = json.loads(action_data)
        except json.JSONDecodeError as e:
            print(f"[ERROR] Failed to parse action JSON: {e}")
            return

    # Extract the 'command' field from the Vedic action object
    command = action_data.get('command')
    message = action_data.get('message', 'No message provided')

    print(f"[ACTUATION LAYER] Processing: {message}")
    
    controller = MockActuatorController()
    controller.execute_command(command)

if __name__ == '__main__':
    print("--- VQIE Actuation Layer Test Block ---")
    
    # Sample command object as generated by the Sanskrit Logic Engine
    sample_action = {
        "type": "emergency_action",
        "message": "High Temperature Warning: Activate Cooling Systems",
        "command": "ACTIVATE_COOLING_FAN"
    }

    process_actuation_command(sample_action)
    print("--- Actuation Layer Test Finished ---")
